### ISSUE TITLE
Differing loadTime value to Chrome DevTools

### ISSUE THREAD

**Issue by foobartel** [addyosmani/timing.js#12]
The values returned from timing.js sometimes differ to those displayed in Chrome DevTools and it's not only a rounding issue, but rather due to a different calculation of load time. It seems that Chrome uses `loadEventEnd - fetchStart` rather than `loadEventEnd - navigationStart` to calculate total load time.

![screen shot 2015-06-03 at 5 35 33 pm](https://cloud.githubusercontent.com/assets/1708876/7958467/6a935526-0a22-11e5-9087-f49e63a47aa9.png)
![screen shot 2015-06-03 at 4 23 42 pm](https://cloud.githubusercontent.com/assets/1708876/7958469/6a94a138-0a22-11e5-9b1d-2b763c0abd03.png)
![screen shot 2015-06-03 at 4 26 21 pm](https://cloud.githubusercontent.com/assets/1708876/7958468/6a942988-0a22-11e5-8f3f-ee00c3a4215f.png)

**Comment by addyosmani** [comment]
Fixed per your patch :)
