### ISSUE TITLE
when i used timing.printTable() ,don't get answer like example

### ISSUE THREAD

**Issue by YellowPure** [addyosmani/timing.js#14]
I changed some code :
`<if (timing.hasOwnProperty(k))  >`
to
`<if (k in timing)>`

then i can use it like `<timing.printTable(window.performace.timing)>`

is that ture?

**Comment by amkirwin** [comment]
I'm also experiencing this.
`performance.timing.hasOwnProperty('...') // always false`

**Comment by amk221** [comment]
I'm also experiencing this.
performance.timing.hasOwnProperty('...') // always false

**Comment by dd1994** [comment]
@amk221 like this https://github.com/addyosmani/timing.js/issues/20 ?

**Comment by amkirwin** [comment]
Yep

**Comment by amk221** [comment]
Yep
