### ISSUE TITLE
chrome.loadTimes() is deprecated

### ISSUE THREAD

**Issue by amk221** [addyosmani/timing.js#35]

**Comment by phil-lgr** [comment]
Link for those landing here https://css-tricks.com/paint-timing-api/

**Comment by sanchezedgar** [comment]
*Bump* Hello!, curious if there are plans to merge and release this?

**Comment by flipjs** [comment]
I think this update was never published to NPM for some reasons. Could it be the package version was not incremented hence npm didnt update? In NPM, it says "1.2.0 • Public • Published 4 years ago".
